### PR TITLE
Bump Hackney to 1.16.0

### PR DESCRIPTION
**Pull request by kitplummer**
Resolves an issue where all requests get munged up with:

```
iex(1)> a = Alpaca.Account.get()
{:error,
 {:options, {:sslv3, {:versions, [:"tlsv1.2", :"tlsv1.1", :tlsv1, :sslv3]}}}}
```

### CODE REVIEW

**Comment by kitplummer** [comment]
Heyo.  So I've fixed/worked-around the test issue.  But now it is bonking on Coveralls POST.  Not sure why that's firing on a PR build.  Maybe make that conditional by branch in config somewhere?

**Review by jrusso1020 — APPROVED** [review]

**Comment by jrusso1020** [comment]
Sorry for the delay! Just noticed this PR, will setup auto assignment for the future so hopefully I see it sooner.

Currently away from my personal computer so will merge this in and update the version sometime next week

**Comment by jrusso1020** [comment]
@kitplummer just published version 1.0.1 with this change!

**Comment by kitplummer** [comment]
Thanks much!

**Pull request merged**
